### ISSUE TITLE
Invalid 'operand' DTD attribute declaration

### ISSUE THREAD

**Issue by natinusala** [mkfs/opdis#16]
Hello,

When I create a XML using opdis, this line is produced somewhere in the header of the file : 

`<!ATTLIST operand type (target|src|dest) "">`

The problem is that an empty string cannot be valid for the default value of the attribute. This leads to parsing errors (on `lxml` especially), with errors such as `invalid default value`.

Could you fix this ?

**Comment by mkfs** [comment]
What's the recommended fix? I'm not an XML guy.

**Comment by natinusala** [comment]
I guess that would be to replace the empty string by an actual default value, but since neither of the current types can be default then you should add `none` to the types and set it as default.

**Comment by mkfs** [comment]
Fix added. Bumped patch number (1.1.3), because why the hell not.
