### ISSUE TITLE
[MacOSX 10.6.8 / brew 0.9.3] build needs ./configure massage

### ISSUE THREAD

**Issue by potorange** [mkfs/opdis#3]
./configure fails with the following in config.log:
<pre>
Undefined symbols:
  "_libintl_dgettext", referenced from:
      _perror_memory in libopcodes.a(dis-buf.o)
      _perror_memory in libopcodes.a(dis-buf.o)
ld: symbol(s) not found
collect2: ld returned 1 exit status
</pre>
and others similar messages related to gettext symbols… I'm able to build opdis on my brewed macosx with the following commands:
<code>
./configure LDFLAGS="-lintl -largp -liberty -L/usr/local/opt/gettext/lib -L/usr/local/opt/argp-standalone/lib -L/usr/local/Cellar/binutils/2.22/lib/x86_64"
</code>
Don't know if you can do anything about it ?
<pre>
HOMEBREW_VERSION: 0.9.3
HEAD: 6b2d52f2afa29d91b97853a7efd744fba01f7ada
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
CPU: dual-core 64-bit penryn
OS X: 10.6.8-i386
Xcode: 3.2.6
GCC-4.0: build 5494
GCC-4.2: build 5666
LLVM-GCC: build 2335
Clang: 1.7 build 77
X11: 2.3.6 => /usr/X11
System Ruby: 1.8.7-358
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/bin/ruby

</pre>

**Comment by mkfs** [comment]
This should all be fixed with the latest commits.
